# Configuration file for automl pipeline.

main_project:
  project_id: # 'TODO(user): set with your Project ID'
  region: 'us-central1' # Currently the only supported location_id is “us-central1”.
  demo_sample_data: # TODO(user): GCS location of patents to process for demo
  demo_dataset_id: # TODO(user): BQ dataset to store information collected from patents for demo
service_acct:
  user_id: # TODO(user) : Set With your GCP Account Email 
  name: 'patent-demo-service-acct'
  description: 'Service-account-for-doc-understanding-demo'
  display_name: 'Patent-Demo-Service-Account'
  key: '../keys/service-acct.json'
pdp_project:
  project_id: 'pdf-processing-219114' # this will change to PDP project later
  dataset_id: 'patent_demo_data_pdp' # this will change once data is PDP'd
  bucket_name: 'patent_demo_data_pdp' # this will change once data is PDP'd
model_imgclassifier:
  pdp_table_id: 'entity_extraction' # table location of PDP data
  model_id: <MODELID_PLACEHOLDER> # TODO: replace with model id when training is complete
  demo_table_id: 'document_classification'
model_objdetect:
  pdp_table_id: 'object_detection' # table location of PDP data
  model_id: <MODELID_PLACEHOLDER>' # TODO: replace with model id when training is complete
  demo_table_id: 'object_detection'
model_textclassifier:
  pdp_table_id: 'text_classification' # table location of PDP data
  model_id: <MODELID_PLACEHOLDER>' # TODO: replace with model id when training is complete
  demo_table_id: 'document_subject'
model_ner:
  pdp_table_id: 'entity_extraction' # table location of PDP data
  model_id: '<NER_MODELID_PLACEHOLDER>' # TODO: replace with model id when training is complete
  demo_table_id: 'ner_results'
  fields_to_extract:
  - field_name: 'file'
  - field_name: 'publication_date'
  - field_name: 'class_international'
    postprocess_fn: 'PostprocessClassification'
  - field_name: 'application_number'
  - field_name: 'filing_date'
  - field_name: 'applicant_line_1'
  - field_name: 'inventor_line_1'
  - field_name: 'title_line_1'
  - field_name: 'number'

