# Configuration file for end-to-end demo.

main_project:
  project_id: # 'TODO (user): set with your Project ID'
  region: #'TODO (user): set with your region'
  input_bucket_name: 'patent_demo_data_pdp' # FROM PDP
  temp_directory: './tmp/google'
  output_directory: 'patent_demo_data/'
service_acct:
  user_id: # TODO(user) : Set With your GCP Account Email
  name: 'patent-demo-service-acct'
  description: 'Service-account-for-doc-understanding-demo'
  display_name: 'Patent-Demo-Service-Account'
  key: '../keys/service-acct.json'
model_imgclassifier:
  project_id: 'pdf-processing-219114'
  dataset_id: 'patent_demo_data_pdp' # dataset location of PDP data
  table_id: 'entity_extraction' # table location of PDP data
  model_id: '<IMAGE_MODELID_PLACEHOLDER>'
model_textclassifier:
  project_id: 'pdf-processing-219114' # project location of PDP data
  dataset_id: 'patent_demo_data_pdp' # dataset location of PDP data 
  table_id: 'text_classification' # table location of PDP data
  model_id: '<TEXT_MODELID_PLACEHOLDER>'
model_ner:
  project_id: 'pdf-processing-219114'
  dataset_id: 'patent_demo_data_pdp' # dataset location of PDP data
  table_id: 'entity_extraction' # table location of PDP data
  model_id: '<NER_MODELID_PLACEHOLDER>'
model_objdetect:
  project_id: 'pdf-processing-219114'
  dataset_id: 'patent_demo_data_pdp' # dataset location of PDP data
  table_id: 'object_detection' # table location of PDP data
  model_id: '<OBJDET_MODELID_PLACEHOLDER>'
fields_to_extract:
  - field_name: 'publication_date'
  - field_name: 'classification_1'
    postprocess_fn: 'PostprocessClassification'
  - field_name: 'classification_2'
    postprocess_fn: 'PostprocessClassification'
  - field_name: 'application_number'
  - field_name: 'filing_date'
  - field_name: 'applicant'
  - field_name: 'inventor'
  - field_name: 'titleFL'
  - field_name: 'publication_number'
