# Configuration file to run from automl-ee (ALL Googlers).

main_project:
  main_project_id: 'automl-ee'
  bucket_name: 'gs://automl-ee'
model_imgclassifier:
  project_id: 'pdf-processing-219114'
  model_id: 'ICN5524972467525006137'
model_textclassifier:
  project_id: 'pdf-processing-219114'
  model_id: 'TCN5951842883293789335'
model_ner:
  project_id: 'pdf-processing-ner'
  model_id: 'TEN3372035036621570048'
model_objdetect:
  project_id: 'pdf-processing-obj-det'
  model_id: 'IOD3595007198641520640'
service_keys:
  key_ner: './document-extraction-demo/0_key/pdf-processing-ner-a0b4d4835aea.json'
  key_objdectect: './document-extraction-demo/0_key/pdf-processing-obj-det-5a69899d02d4.json'
  key_bq_and_gcs: './document-extraction-demo/0_key/automl-ee-8d6e8d48ba44.json' # Also AutoML Vision and AutoML Text.
truth_csv: "gs://automl-ee/input_data_pdf/truth_data_feb182019.csv"
fields_to_extract:
  - field_name: 'publication_date'
  - field_name: 'classification_1'
    postprocess_fn: 'PostprocessClassification'
  - field_name: 'classification_2'
    postprocess_fn: 'PostprocessClassification'
  - field_name: 'application_number'
  - field_name: 'filing_date'
  - field_name: 'applicant'
  - field_name: 'inventor'
  - field_name: 'titleFL'
  - field_name: 'publication_number'
